sudo: false
language: scala
scala:
- 2.12.10
jdk:
- openjdk11

before_install:
- git fetch --tags

stages:
- name: test
- name: release
  if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
  - stage: test
    name: formatting
    script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - stage: test
    name: test
    script: sbt ++$TRAVIS_SCALA_VERSION test
  - stage: release
    name: release
    script: sbt ci-release

cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.sbt"

before_cache:
- find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
  - secure: h4MAAh76O0Jjmb8HwpsZBS+9ozs30QH823cVbMxLkGQarjNv2Eyl2KPm1m5Q0DP8Mc4iDhckGWQm2Qw/o6Pp9sD01VOdUU8V1r9rC7ELAgFVbGJW+DdDnKBdQuozCSqehYHsyoX8NehYVgPnvrY6SHdbNhIIldPEPKCVuoecQldL1Vi1aUYhOiXOIiW98mJq8g2QWnR0yd8uuwaKQGKZfurc5i9KtFkr55TdfpLNKnV6Jggp0P8y7rZtZg7RYWbS06CNaumNW2ngnUYkYDok9pdcKFjyqDjDFk3/9wblNxbzBGJEIfUEkpmpLlbAxXM4mWfM1L07ReJXTY7zuVzoS/ke/y0IjXQVGpx7SUHOFB7VIww3OJNhE/O59SjAK9V2mKGJcpRKwp/IRLmziTYKw1yC87xU0pKiiyNrDsLhSCQVt0i0sfzxe0SAqfJdwKUAuBYqHCxvXDw+jJEmOAxpRRSKqI2sUq2gnVXs7WmsW1rdh/yNeF0pJ3BbRYSKtMhOdtrV0GHBm87s7dRtFhgJoQ/a+zSYEKFKOleQE6kcXVGC/yaPN6SbGcOlOLy2LWuHuAvEePjLB1WKP7lOvZq0oYPd/5F4TSyxXHy/qE+wLX/VORksTdH1dcsNao78UVUwg5zt5dhvLyUSAQIPMh5CYZedlwhqSgbV6ij31tDFAoU=
  - secure: UZk4sbcghg4n+Qb0BzQZRD6Ls4keNxaSmI9r/wj3NIiTlza9vG+/mC6Ddx4gFXi53TiMI7e/odDELL5cYilHFimHBQ3agHCjk/JQ5qyF8CZY0jjn4XX28YJEIlI6pUvSDKj1k2VYrPOYR+BmsMz/r1BSCYPffHaziIqKqeFzyfBSPz7z5Z8D2V42jw4I6mm5RZP9+PT9b8vPG2SkGuiOo3m+FcWUI49ekmwBwXzt9iS/QOuVzvEs5K6S2eIl486wlP10yF6VqhUgz9MP2qBgmYD2jFirmwb0WkRVh44ai7jTcYkawdFOz1AaRGosta7pQSOZitnhGvFz5k5xfDEkA7qh22CpLDfLApzJ01Bt1/Q8GM8beSJ0MZ/U06Uywfhc3h3TLszX/8HE6ruq9ut5P+eCzIDA/mT8FWRoBgrsy4a3kTmmOn/nBudDF1wuu8ZAuWNLKKiWPiYNZIsg4NGykOrBK8ufSb3ybh756yCB0rb4A0TEygHh5qcItxBt0ZB9rSkCGDksIZfR+hlHPn6u4SN4auKoDKYEaT5OnLFU60yYld3sn1aG/1sH7zFOiLQSvf7gWBW12+xIecwRmYfFSH//G++vb9EnTxEFQpsQjg/q67fYTaB9zPXPGihQJmbPLvtQFq7gYPhTJ+RwuSvJC1ZSAO09DsR11dRIduD4wxs=
  - secure: WAEpK3xpedP5IxivLEzyAMlPiolUAPJXjc8Jg9j9xK5Xt0ElTZn/n6l/iatCfwSh6ZbG6vQVvzltK+k/Z44ha/1MO+tRkWawTf7CsUgkG6yNX62Nfy19cnrwD+joEPb5U64zG0qS5KV//Xw82vVJCLVwI4acs1nmfTHqC8stu4/YPj8hleIQfoORcFyLnDDv/rM0rJNZNdPuhUDdesCEPTjmYyC/m8uGcVEgk3JhMqv3P+/pWSDEgAFMMXlwNlETSbuLRGKbwgIhyYDGA++HAPSrOI819uIVjwHq1+NtMmYs8P+R0pM7Bp94RMJv6gkcTHBxGqmRnBtgGp9lVsUN+BiJWzoiIewYYkOkUF/GLc7znPWv7NoItxF8cYhCoLguydsxuSvWryieBK5ilw51So4NPwyhBAqvkAgW3ngZxmm5gzb92JFrDMG4O/89Bs11GQ7eQ3ulA1Cy0wS88ACJ8uyn4AL2k01Xz72SL9yh82uFmOpDIDwvtvGFw9QdbR3J2HyrxcMqVFcQUvJI0epIcQlYxWiyghI0pdWAhm2U2POnrob91dCJCzl92nFGQJX7/+xzwWtE5GL4bf51hi1W3RMFCQ4P0jzGo3Tl888N5A2karoCDWKf3D8CHuyWi9Cos0Gn1Nc9fN3JtyfARnlAlDaNwCHnb3Amj/Rr4ue2ZXo=
