name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v2
      with:
        java-version: openjdk@1.11
    - name: Compile
      run: sbt clean +compile +test
